version: '3'

tasks:
  clean:
    desc: Clean generated artifacts
    cmds:
      - rm -f *.snap
      - rm -rf parts
      - rm -rf prime
      - rm -rf stage
      - rm -rf snap/.snapcraft

  build:
    desc: Build Snap package
    cmds:
      - snapcraft
