name: task
version: v3.9.0
title: Task
summary: A task runner / simpler Make alternative written in Go
description: |
  Task is a simple tool that allows you to easily run development and build
  tasks. Task is written in Golang, but can be used to develop any language.
  It aims to be simpler and easier to use then GNU Make.
license: MIT

base: core18
grade: stable
confinement: classic

architectures:
  - build-on: amd64
  - build-on: i386

parts:
  task:
    plugin: dump
    source:
      - on amd64: https://github.com/go-task/task/releases/download/$SNAPCRAFT_PROJECT_VERSION/task_linux_amd64.tar.gz
      - on i386: https://github.com/go-task/task/releases/download/$SNAPCRAFT_PROJECT_VERSION/task_linux_386.tar.gz

apps:
  task:
    command: task
