name: task
version: 'v1.4.4'
summary: A task runner / simpler Make alternative written in Go
description: |
  Task is a simple tool that allows you to easily run development and build
  tasks. Task is written in Golang, but can be used to develop any language.
  It aims to be simpler and easier to use then GNU Make.

grade: stable
confinement: classic

parts:
  task:
    plugin: nil
    build-packages:
      - curl
    build: |
      set -x

      if [ "$(arch)" = "x86_64" ]; then
        ARCH=amd64
      elif [ "$(arch)" = "i686" ]; then
        ARCH=386
      else
        echo "$(arch) not supported"
        exit 1
      fi

      URL="https://github.com/go-task/task/releases/download/$SNAPCRAFT_PROJECT_VERSION/task_linux_$ARCH.tar.gz"
      curl -Lo- "$URL" | tar -C $SNAPCRAFT_PART_INSTALL -zxvf -

apps:
  task:
    command: task
